# Generated by Django 3.0.8 on 2021-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAS_Rest_Api', '0002_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
