# Generated by Django 3.1.4 on 2021-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAS_Rest_Api', '0004_auto_20210529_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='media\\media\\Blogs\\img-11.jpg', upload_to='media/Blogs'),
        ),
    ]
